In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [3]:
test = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")
test.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

convert text to lower case <br>
stemming <br>
stop words removal <br>
tf idf <br>

In [4]:
text = train["text"].str.lower()
text.head()

0    our deeds are the reason of this #earthquake m...
1               forest fire near la ronge sask. canada
2    all residents asked to 'shelter in place' are ...
3    13,000 people receive #wildfires evacuation or...
4    just got sent this photo from ruby #alaska as ...
Name: text, dtype: object

In [5]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [6]:
from spacy.lang.en.stop_words import STOP_WORDS
import re
for i in range(len(text)):
    doc = nlp(text[i])
    empty_list = []
    for token in doc:
        if token.is_stop == False:
            t = token.lemma_
            t = re.sub(r"[^a-zA-Z ]", "", t)
            empty_list.append(t)
    final_string = ' '.join(map(str,empty_list))
    text[i] = final_string

In [7]:
text.head()

0                deed reason  earthquake allah forgive
1               forest fire near la ronge sask  canada
2    resident ask  shelter place  notify officer  e...
3     people receive  wildfire evacuation order cal...
4    got send photo ruby  alaska smoke  wildfire po...
Name: text, dtype: object

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(text)
x = x.toarray()
x = pd.DataFrame(x)
x.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   18749  18750  18751  18752  18753  18754  18755  18756  18757  18758  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 18759 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x.loc[:,0:10000], train['target'],
                                                    test_size=0.3,
                                                    random_state=0,
                                                    stratify=train['target'])

In [10]:
x_train.head()

0      1      2      3      4      5      6      7      8      9      \
4812    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2080    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
652     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3528    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3007    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  9991   9992   9993   9994   9995   9996   9997   9998   9999   \
4812  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2080  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
652   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3528  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3007  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      10000  
4812    0.0  
2080    0.0  
652     0.0  
3528    0.0  
3007    0.0  

[5 rows x 10001 columns]

In [11]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(x_train, y_train)
pred = clf.predict(x_test)
pred

array([1, 1, 0, ..., 1, 1, 0])

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[1215,   88],
       [ 493,  488]])

In [13]:
clf1 = LogisticRegression(random_state=0).fit(x.loc[:,0:10000], train['target'])

In [14]:
pred_1 = test['text'].str.lower()
pred_1

0                      just happened a terrible car crash
1       heard about #earthquake is different cities, s...
2       there is a forest fire at spot pond, geese are...
3                apocalypse lighting. #spokane #wildfires
4           typhoon soudelor kills 28 in china and taiwan
                              ...                        
3258    earthquake safety los angeles ‰ûò safety faste...
3259    storm in ri worse than last hurricane. my city...
3260    green line derailment in chicago http://t.co/u...
3261    meg issues hazardous weather outlook (hwo) htt...
3262    #cityofcalgary has activated its municipal eme...
Name: text, Length: 3263, dtype: object

In [15]:
for i in range(len(pred_1)):
    doc = nlp(pred_1[i])
    empty_list = []
    for token in doc:
        if token.is_stop == False:
            t = token.lemma_
            t = re.sub(r"[^a-zA-Z ]", "", t)
            empty_list.append(t)
    final_string = ' '.join(map(str,empty_list))
    pred_1[i] = final_string

x1 = v.fit_transform(pred_1)
x1 = x1.toarray()
x1 = pd.DataFrame(x1)
x1.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   10466  10467  10468  10469  10470  10471  10472  10473  10474  10475  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 10476 columns]

In [16]:
pred_2 = clf.predict(x1.loc[:,0:10000])
pred_2

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
subfile = pd.DataFrame(columns = ['id', 'target'])

In [18]:
subfile['id'] = test['id']
subfile['target'] = pred_2
subfile.head()

id  target
0   0       0
1   2       0
2   3       0
3   9       0
4  11       0

In [19]:
subfile.to_csv("lr_1.csv", index=False)