<a href="https://www.kaggle.com/code/maheswarareddyp/pytorch-basics?scriptVersionId=137253339" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import torch

In [2]:
x = torch.Tensor(10).random_(0, 10)
#x.to('cuda')
x.to('cpu')

tensor([9., 2., 9., 4., 6., 5., 1., 4., 7., 2.])

In [3]:
#torch.cuda.is_avialbale()
# to check GPU's in a  system

In [4]:
tensor1 = torch.Tensor([1,2,3,4])
print (tensor1)
tensor1.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [5]:
tensor1 = torch.Tensor([[1,2,3,4],[5,6,7,8]])
print (tensor1)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


In [6]:
tensor1.shape

torch.Size([2, 4])

In [7]:
e1 = torch.randn(3,3)
e1

tensor([[-1.9494,  1.4311,  0.1742],
        [ 0.7974,  0.9325,  0.3399],
        [ 0.9512, -0.1408,  0.3542]])

In [8]:
e2 = torch.randint(low= 0, high= 10, size = (3,3)).type(torch.FloatTensor)
e2

tensor([[6., 2., 6.],
        [1., 4., 9.],
        [3., 1., 5.]])

In [9]:
a = torch.tensor([5.0, 3.0], requires_grad=True)
b = torch.tensor([1.0, 4.0])
ab = ((a + b) ** 2).sum()
ab.backward()

In [10]:
ab.grad

/tmp/ipykernel_20/1459142135.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  ab.grad


In [11]:
a.grad.data

tensor([12., 14.])

In [12]:
import torch.nn as nn
input_units = 10
hidden_units = 3
output_units = 1
model = nn.Sequential(nn.Linear(input_units, hidden_units), \
                      nn.ReLU(), \
                      nn.Linear(hidden_units, output_units), \
                      nn.Sigmoid())
loss_funct = nn.MSELoss()