In [1]:
import tensorflow as tf

2024-02-22 13:52:09.084382: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-22 13:52:09.084517: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-22 13:52:09.236792: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
tf.__version__

'2.15.0'

In [3]:
tensor1 = tf.Variable([1,2,3], dtype = tf.int32, name = "My_Tensor", Trainable = True)

In [4]:
tensor1

<tf.Variable 'My_Tensor:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
tensor1.shape

TensorShape([3])

In [6]:
tensor1.get_shape

<bound method Variable.get_shape of <tf.Variable 'My_Tensor:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>>

In [7]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Create a scalar to store the votes cast for Candidate 1 of political party X in
district A, that is, 4113, and check its shape and rank.

In [8]:
candidate1 = tf.Variable([4113], dtype = tf.int32, name = 'Candidate1', trainable = True)
candidate1.shape

TensorShape([1])

• Create a vector to represent the proportion of votes cast for three different
candidates of political party X in district A and check its shape and rank.

In [9]:
portionofVotes_partyX = tf.Variable([4113, 7511, 6529], dtype = tf.int32, name="PortionOfVotes", trainable = True)
portionofVotes_partyX.shape

TensorShape([3])

Create a matrix to represent the votes cast for three different candidates of
political parties X and Y and check its shape and rank.

In [10]:
diffCand = tf.Variable([[4113, 3870], [7511, 6725], [6529, 3870]], dtype = tf.int32, name = 'DiffCand', trinabale = True)
diffCand.shape

TensorShape([3, 2])

In [11]:
diffCand

<tf.Variable 'DiffCand:0' shape=(3, 2) dtype=int32, numpy=
array([[4113, 3870],
       [7511, 6725],
       [6529, 3870]], dtype=int32)>

In [12]:
tf.rank(diffCand)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Create a tensor to represent the votes cast for three different candidates in two
different districts, for three political parties, and check its shape and rank.

In [13]:
p3C3 = tf.Variable([[[4113, 3870, 5102], [7511, 6725, 7038], [6529, 6962, 6591]], [[3611, 951, 870], [5901, 1208, 645], [6235, 1098, 948]]], dtype = tf.int32, trainable = True, name = "3Districts3Parties3Candidates")
p3C3.shape

TensorShape([2, 3, 3])

In [14]:
p3C3

<tf.Variable '3Districts3Parties3Candidates:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[4113, 3870, 5102],
        [7511, 6725, 7038],
        [6529, 6962, 6591]],

       [[3611,  951,  870],
        [5901, 1208,  645],
        [6235, 1098,  948]]], dtype=int32)>

In [15]:
tf.rank(p3C3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
tf.rank(p3C3).numpy()

3

In [17]:
p3C3.shape.as_list()

[2, 3, 3]

Tensor Addition

In [18]:
t1 = tf.Variable([1,2,3])
t2 = tf.Variable([2,3,4])

In [19]:
t_add = tf.add(t1, t2)
t_add

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [20]:
t_add_sign = t1 + t2
t_add_sign

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

***Reshaping***

In [21]:
t3 = tf.Variable([1,2,3,4,5, 6], dtype = tf.int16)
t3

<tf.Variable 'Variable:0' shape=(6,) dtype=int16, numpy=array([1, 2, 3, 4, 5, 6], dtype=int16)>

In [22]:
tf.reshape(t3, shape = [3,2])

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

***Tensor Transposition***